/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-02 at 03:42:13 UTC 
 * Modify at your own risk.
 */

package com.mycompany.services.listaroendpoint;

/**
 * Service definition for Listaroendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ListaroendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Listaroendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the listaroendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://omega-episode-92402.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "listaroendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Listaroendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Listaroendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getListarO".
   *
   * This request holds the parameters needed by the listaroendpoint server.  After setting any
   * optional parameters, call the {@link GetListarO#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetListarO getListarO(java.lang.Long id) throws java.io.IOException {
    GetListarO result = new GetListarO(id);
    initialize(result);
    return result;
  }

  public class GetListarO extends ListaroendpointRequest<com.mycompany.services.listaroendpoint.model.ListarO> {

    private static final String REST_PATH = "listaro/{id}";

    /**
     * Create a request for the method "getListarO".
     *
     * This request holds the parameters needed by the the listaroendpoint server.  After setting any
     * optional parameters, call the {@link GetListarO#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetListarO#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetListarO(java.lang.Long id) {
      super(Listaroendpoint.this, "GET", REST_PATH, null, com.mycompany.services.listaroendpoint.model.ListarO.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetListarO setAlt(java.lang.String alt) {
      return (GetListarO) super.setAlt(alt);
    }

    @Override
    public GetListarO setFields(java.lang.String fields) {
      return (GetListarO) super.setFields(fields);
    }

    @Override
    public GetListarO setKey(java.lang.String key) {
      return (GetListarO) super.setKey(key);
    }

    @Override
    public GetListarO setOauthToken(java.lang.String oauthToken) {
      return (GetListarO) super.setOauthToken(oauthToken);
    }

    @Override
    public GetListarO setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetListarO) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetListarO setQuotaUser(java.lang.String quotaUser) {
      return (GetListarO) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetListarO setUserIp(java.lang.String userIp) {
      return (GetListarO) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetListarO setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetListarO set(String parameterName, Object value) {
      return (GetListarO) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertListarO".
   *
   * This request holds the parameters needed by the listaroendpoint server.  After setting any
   * optional parameters, call the {@link InsertListarO#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.mycompany.services.listaroendpoint.model.ListarO}
   * @return the request
   */
  public InsertListarO insertListarO(com.mycompany.services.listaroendpoint.model.ListarO content) throws java.io.IOException {
    InsertListarO result = new InsertListarO(content);
    initialize(result);
    return result;
  }

  public class InsertListarO extends ListaroendpointRequest<com.mycompany.services.listaroendpoint.model.ListarO> {

    private static final String REST_PATH = "listaro";

    /**
     * Create a request for the method "insertListarO".
     *
     * This request holds the parameters needed by the the listaroendpoint server.  After setting any
     * optional parameters, call the {@link InsertListarO#execute()} method to invoke the remote
     * operation. <p> {@link InsertListarO#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.mycompany.services.listaroendpoint.model.ListarO}
     * @since 1.13
     */
    protected InsertListarO(com.mycompany.services.listaroendpoint.model.ListarO content) {
      super(Listaroendpoint.this, "POST", REST_PATH, content, com.mycompany.services.listaroendpoint.model.ListarO.class);
    }

    @Override
    public InsertListarO setAlt(java.lang.String alt) {
      return (InsertListarO) super.setAlt(alt);
    }

    @Override
    public InsertListarO setFields(java.lang.String fields) {
      return (InsertListarO) super.setFields(fields);
    }

    @Override
    public InsertListarO setKey(java.lang.String key) {
      return (InsertListarO) super.setKey(key);
    }

    @Override
    public InsertListarO setOauthToken(java.lang.String oauthToken) {
      return (InsertListarO) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertListarO setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertListarO) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertListarO setQuotaUser(java.lang.String quotaUser) {
      return (InsertListarO) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertListarO setUserIp(java.lang.String userIp) {
      return (InsertListarO) super.setUserIp(userIp);
    }

    @Override
    public InsertListarO set(String parameterName, Object value) {
      return (InsertListarO) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listListarO".
   *
   * This request holds the parameters needed by the listaroendpoint server.  After setting any
   * optional parameters, call the {@link ListListarO#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListListarO listListarO() throws java.io.IOException {
    ListListarO result = new ListListarO();
    initialize(result);
    return result;
  }

  public class ListListarO extends ListaroendpointRequest<com.mycompany.services.listaroendpoint.model.CollectionResponseListarO> {

    private static final String REST_PATH = "listaro";

    /**
     * Create a request for the method "listListarO".
     *
     * This request holds the parameters needed by the the listaroendpoint server.  After setting any
     * optional parameters, call the {@link ListListarO#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListListarO#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListListarO() {
      super(Listaroendpoint.this, "GET", REST_PATH, null, com.mycompany.services.listaroendpoint.model.CollectionResponseListarO.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListListarO setAlt(java.lang.String alt) {
      return (ListListarO) super.setAlt(alt);
    }

    @Override
    public ListListarO setFields(java.lang.String fields) {
      return (ListListarO) super.setFields(fields);
    }

    @Override
    public ListListarO setKey(java.lang.String key) {
      return (ListListarO) super.setKey(key);
    }

    @Override
    public ListListarO setOauthToken(java.lang.String oauthToken) {
      return (ListListarO) super.setOauthToken(oauthToken);
    }

    @Override
    public ListListarO setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListListarO) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListListarO setQuotaUser(java.lang.String quotaUser) {
      return (ListListarO) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListListarO setUserIp(java.lang.String userIp) {
      return (ListListarO) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String categoria;

    /**

     */
    public java.lang.String getCategoria() {
      return categoria;
    }

    public ListListarO setCategoria(java.lang.String categoria) {
      this.categoria = categoria;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListListarO setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String lugar;

    /**

     */
    public java.lang.String getLugar() {
      return lugar;
    }

    public ListListarO setLugar(java.lang.String lugar) {
      this.lugar = lugar;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer estado;

    /**

     */
    public java.lang.Integer getEstado() {
      return estado;
    }

    public ListListarO setEstado(java.lang.Integer estado) {
      this.estado = estado;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListListarO setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListListarO set(String parameterName, Object value) {
      return (ListListarO) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeListarO".
   *
   * This request holds the parameters needed by the listaroendpoint server.  After setting any
   * optional parameters, call the {@link RemoveListarO#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveListarO removeListarO(java.lang.Long id) throws java.io.IOException {
    RemoveListarO result = new RemoveListarO(id);
    initialize(result);
    return result;
  }

  public class RemoveListarO extends ListaroendpointRequest<Void> {

    private static final String REST_PATH = "listaro/{id}";

    /**
     * Create a request for the method "removeListarO".
     *
     * This request holds the parameters needed by the the listaroendpoint server.  After setting any
     * optional parameters, call the {@link RemoveListarO#execute()} method to invoke the remote
     * operation. <p> {@link RemoveListarO#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveListarO(java.lang.Long id) {
      super(Listaroendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveListarO setAlt(java.lang.String alt) {
      return (RemoveListarO) super.setAlt(alt);
    }

    @Override
    public RemoveListarO setFields(java.lang.String fields) {
      return (RemoveListarO) super.setFields(fields);
    }

    @Override
    public RemoveListarO setKey(java.lang.String key) {
      return (RemoveListarO) super.setKey(key);
    }

    @Override
    public RemoveListarO setOauthToken(java.lang.String oauthToken) {
      return (RemoveListarO) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveListarO setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveListarO) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveListarO setQuotaUser(java.lang.String quotaUser) {
      return (RemoveListarO) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveListarO setUserIp(java.lang.String userIp) {
      return (RemoveListarO) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveListarO setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveListarO set(String parameterName, Object value) {
      return (RemoveListarO) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateListarO".
   *
   * This request holds the parameters needed by the listaroendpoint server.  After setting any
   * optional parameters, call the {@link UpdateListarO#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.mycompany.services.listaroendpoint.model.ListarO}
   * @return the request
   */
  public UpdateListarO updateListarO(com.mycompany.services.listaroendpoint.model.ListarO content) throws java.io.IOException {
    UpdateListarO result = new UpdateListarO(content);
    initialize(result);
    return result;
  }

  public class UpdateListarO extends ListaroendpointRequest<com.mycompany.services.listaroendpoint.model.ListarO> {

    private static final String REST_PATH = "listaro";

    /**
     * Create a request for the method "updateListarO".
     *
     * This request holds the parameters needed by the the listaroendpoint server.  After setting any
     * optional parameters, call the {@link UpdateListarO#execute()} method to invoke the remote
     * operation. <p> {@link UpdateListarO#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.mycompany.services.listaroendpoint.model.ListarO}
     * @since 1.13
     */
    protected UpdateListarO(com.mycompany.services.listaroendpoint.model.ListarO content) {
      super(Listaroendpoint.this, "PUT", REST_PATH, content, com.mycompany.services.listaroendpoint.model.ListarO.class);
    }

    @Override
    public UpdateListarO setAlt(java.lang.String alt) {
      return (UpdateListarO) super.setAlt(alt);
    }

    @Override
    public UpdateListarO setFields(java.lang.String fields) {
      return (UpdateListarO) super.setFields(fields);
    }

    @Override
    public UpdateListarO setKey(java.lang.String key) {
      return (UpdateListarO) super.setKey(key);
    }

    @Override
    public UpdateListarO setOauthToken(java.lang.String oauthToken) {
      return (UpdateListarO) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateListarO setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateListarO) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateListarO setQuotaUser(java.lang.String quotaUser) {
      return (UpdateListarO) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateListarO setUserIp(java.lang.String userIp) {
      return (UpdateListarO) super.setUserIp(userIp);
    }

    @Override
    public UpdateListarO set(String parameterName, Object value) {
      return (UpdateListarO) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Listaroendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Listaroendpoint}. */
    @Override
    public Listaroendpoint build() {
      return new Listaroendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ListaroendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setListaroendpointRequestInitializer(
        ListaroendpointRequestInitializer listaroendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(listaroendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
