/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-05-29 at 14:09:59 UTC 
 * Modify at your own risk.
 */

package com.example.mateobadillo.ingesoft.registraruendpoint.model;

/**
 * Model definition for RegistrarU.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the registraruendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RegistrarU extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long codigo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String conrasena;

  /**
   * @return value or {@code null} for none
   */
  public Long getCodigo() {
    return codigo;
  }

  /**
   * @param codigo codigo or {@code null} for none
   */
  public RegistrarU setCodigo(Long codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getConrasena() {
    return conrasena;
  }

  /**
   * @param conrasena conrasena or {@code null} for none
   */
  public RegistrarU setConrasena(String conrasena) {
    this.conrasena = conrasena;
    return this;
  }

  @Override
  public RegistrarU set(String fieldName, Object value) {
    return (RegistrarU) super.set(fieldName, value);
  }

  @Override
  public RegistrarU clone() {
    return (RegistrarU) super.clone();
  }

}
