/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-03 at 01:00:08 UTC 
 * Modify at your own risk.
 */

package com.example.mateobadillo.ingesoft.objetoperdidoendpoint;

/**
 * Service definition for Objetoperdidoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ObjetoperdidoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Objetoperdidoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the objetoperdidoendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://omega-episode-92402.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "objetoperdidoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Objetoperdidoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Objetoperdidoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getObjetoPerdido".
   *
   * This request holds the parameters needed by the objetoperdidoendpoint server.  After setting any
   * optional parameters, call the {@link GetObjetoPerdido#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetObjetoPerdido getObjetoPerdido(java.lang.Long id) throws java.io.IOException {
    GetObjetoPerdido result = new GetObjetoPerdido(id);
    initialize(result);
    return result;
  }

  public class GetObjetoPerdido extends ObjetoperdidoendpointRequest<com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido> {

    private static final String REST_PATH = "objetoperdido/{id}";

    /**
     * Create a request for the method "getObjetoPerdido".
     *
     * This request holds the parameters needed by the the objetoperdidoendpoint server.  After
     * setting any optional parameters, call the {@link GetObjetoPerdido#execute()} method to invoke
     * the remote operation. <p> {@link GetObjetoPerdido#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetObjetoPerdido(java.lang.Long id) {
      super(Objetoperdidoendpoint.this, "GET", REST_PATH, null, com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetObjetoPerdido setAlt(java.lang.String alt) {
      return (GetObjetoPerdido) super.setAlt(alt);
    }

    @Override
    public GetObjetoPerdido setFields(java.lang.String fields) {
      return (GetObjetoPerdido) super.setFields(fields);
    }

    @Override
    public GetObjetoPerdido setKey(java.lang.String key) {
      return (GetObjetoPerdido) super.setKey(key);
    }

    @Override
    public GetObjetoPerdido setOauthToken(java.lang.String oauthToken) {
      return (GetObjetoPerdido) super.setOauthToken(oauthToken);
    }

    @Override
    public GetObjetoPerdido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetObjetoPerdido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetObjetoPerdido setQuotaUser(java.lang.String quotaUser) {
      return (GetObjetoPerdido) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetObjetoPerdido setUserIp(java.lang.String userIp) {
      return (GetObjetoPerdido) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetObjetoPerdido setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetObjetoPerdido set(String parameterName, Object value) {
      return (GetObjetoPerdido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertObjetoPerdido".
   *
   * This request holds the parameters needed by the objetoperdidoendpoint server.  After setting any
   * optional parameters, call the {@link InsertObjetoPerdido#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido}
   * @return the request
   */
  public InsertObjetoPerdido insertObjetoPerdido(com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido content) throws java.io.IOException {
    InsertObjetoPerdido result = new InsertObjetoPerdido(content);
    initialize(result);
    return result;
  }

  public class InsertObjetoPerdido extends ObjetoperdidoendpointRequest<com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido> {

    private static final String REST_PATH = "objetoperdido";

    /**
     * Create a request for the method "insertObjetoPerdido".
     *
     * This request holds the parameters needed by the the objetoperdidoendpoint server.  After
     * setting any optional parameters, call the {@link InsertObjetoPerdido#execute()} method to
     * invoke the remote operation. <p> {@link InsertObjetoPerdido#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido}
     * @since 1.13
     */
    protected InsertObjetoPerdido(com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido content) {
      super(Objetoperdidoendpoint.this, "POST", REST_PATH, content, com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido.class);
    }

    @Override
    public InsertObjetoPerdido setAlt(java.lang.String alt) {
      return (InsertObjetoPerdido) super.setAlt(alt);
    }

    @Override
    public InsertObjetoPerdido setFields(java.lang.String fields) {
      return (InsertObjetoPerdido) super.setFields(fields);
    }

    @Override
    public InsertObjetoPerdido setKey(java.lang.String key) {
      return (InsertObjetoPerdido) super.setKey(key);
    }

    @Override
    public InsertObjetoPerdido setOauthToken(java.lang.String oauthToken) {
      return (InsertObjetoPerdido) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertObjetoPerdido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertObjetoPerdido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertObjetoPerdido setQuotaUser(java.lang.String quotaUser) {
      return (InsertObjetoPerdido) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertObjetoPerdido setUserIp(java.lang.String userIp) {
      return (InsertObjetoPerdido) super.setUserIp(userIp);
    }

    @Override
    public InsertObjetoPerdido set(String parameterName, Object value) {
      return (InsertObjetoPerdido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listObjetoPerdido".
   *
   * This request holds the parameters needed by the objetoperdidoendpoint server.  After setting any
   * optional parameters, call the {@link ListObjetoPerdido#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListObjetoPerdido listObjetoPerdido() throws java.io.IOException {
    ListObjetoPerdido result = new ListObjetoPerdido();
    initialize(result);
    return result;
  }

  public class ListObjetoPerdido extends ObjetoperdidoendpointRequest<com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.CollectionResponseObjetoPerdido> {

    private static final String REST_PATH = "objetoperdido";

    /**
     * Create a request for the method "listObjetoPerdido".
     *
     * This request holds the parameters needed by the the objetoperdidoendpoint server.  After
     * setting any optional parameters, call the {@link ListObjetoPerdido#execute()} method to invoke
     * the remote operation. <p> {@link ListObjetoPerdido#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListObjetoPerdido() {
      super(Objetoperdidoendpoint.this, "GET", REST_PATH, null, com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.CollectionResponseObjetoPerdido.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListObjetoPerdido setAlt(java.lang.String alt) {
      return (ListObjetoPerdido) super.setAlt(alt);
    }

    @Override
    public ListObjetoPerdido setFields(java.lang.String fields) {
      return (ListObjetoPerdido) super.setFields(fields);
    }

    @Override
    public ListObjetoPerdido setKey(java.lang.String key) {
      return (ListObjetoPerdido) super.setKey(key);
    }

    @Override
    public ListObjetoPerdido setOauthToken(java.lang.String oauthToken) {
      return (ListObjetoPerdido) super.setOauthToken(oauthToken);
    }

    @Override
    public ListObjetoPerdido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListObjetoPerdido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListObjetoPerdido setQuotaUser(java.lang.String quotaUser) {
      return (ListObjetoPerdido) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListObjetoPerdido setUserIp(java.lang.String userIp) {
      return (ListObjetoPerdido) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListObjetoPerdido setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListObjetoPerdido setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListObjetoPerdido set(String parameterName, Object value) {
      return (ListObjetoPerdido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeObjetoPerdido".
   *
   * This request holds the parameters needed by the objetoperdidoendpoint server.  After setting any
   * optional parameters, call the {@link RemoveObjetoPerdido#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @param codigoUsuario
   * @return the request
   */
  public RemoveObjetoPerdido removeObjetoPerdido(java.lang.Long id, java.lang.String codigoUsuario) throws java.io.IOException {
    RemoveObjetoPerdido result = new RemoveObjetoPerdido(id, codigoUsuario);
    initialize(result);
    return result;
  }

  public class RemoveObjetoPerdido extends ObjetoperdidoendpointRequest<Void> {

    private static final String REST_PATH = "objetoperdido/{id}/{codigo_usuario}";

    /**
     * Create a request for the method "removeObjetoPerdido".
     *
     * This request holds the parameters needed by the the objetoperdidoendpoint server.  After
     * setting any optional parameters, call the {@link RemoveObjetoPerdido#execute()} method to
     * invoke the remote operation. <p> {@link RemoveObjetoPerdido#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @param codigoUsuario
     * @since 1.13
     */
    protected RemoveObjetoPerdido(java.lang.Long id, java.lang.String codigoUsuario) {
      super(Objetoperdidoendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.codigoUsuario = com.google.api.client.util.Preconditions.checkNotNull(codigoUsuario, "Required parameter codigoUsuario must be specified.");
    }

    @Override
    public RemoveObjetoPerdido setAlt(java.lang.String alt) {
      return (RemoveObjetoPerdido) super.setAlt(alt);
    }

    @Override
    public RemoveObjetoPerdido setFields(java.lang.String fields) {
      return (RemoveObjetoPerdido) super.setFields(fields);
    }

    @Override
    public RemoveObjetoPerdido setKey(java.lang.String key) {
      return (RemoveObjetoPerdido) super.setKey(key);
    }

    @Override
    public RemoveObjetoPerdido setOauthToken(java.lang.String oauthToken) {
      return (RemoveObjetoPerdido) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveObjetoPerdido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveObjetoPerdido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveObjetoPerdido setQuotaUser(java.lang.String quotaUser) {
      return (RemoveObjetoPerdido) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveObjetoPerdido setUserIp(java.lang.String userIp) {
      return (RemoveObjetoPerdido) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveObjetoPerdido setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key("codigo_usuario")
    private java.lang.String codigoUsuario;

    /**

     */
    public java.lang.String getCodigoUsuario() {
      return codigoUsuario;
    }

    public RemoveObjetoPerdido setCodigoUsuario(java.lang.String codigoUsuario) {
      this.codigoUsuario = codigoUsuario;
      return this;
    }

    @Override
    public RemoveObjetoPerdido set(String parameterName, Object value) {
      return (RemoveObjetoPerdido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateObjetoPerdido".
   *
   * This request holds the parameters needed by the objetoperdidoendpoint server.  After setting any
   * optional parameters, call the {@link UpdateObjetoPerdido#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido}
   * @return the request
   */
  public UpdateObjetoPerdido updateObjetoPerdido(com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido content) throws java.io.IOException {
    UpdateObjetoPerdido result = new UpdateObjetoPerdido(content);
    initialize(result);
    return result;
  }

  public class UpdateObjetoPerdido extends ObjetoperdidoendpointRequest<com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido> {

    private static final String REST_PATH = "objetoperdido";

    /**
     * Create a request for the method "updateObjetoPerdido".
     *
     * This request holds the parameters needed by the the objetoperdidoendpoint server.  After
     * setting any optional parameters, call the {@link UpdateObjetoPerdido#execute()} method to
     * invoke the remote operation. <p> {@link UpdateObjetoPerdido#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido}
     * @since 1.13
     */
    protected UpdateObjetoPerdido(com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido content) {
      super(Objetoperdidoendpoint.this, "PUT", REST_PATH, content, com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model.ObjetoPerdido.class);
    }

    @Override
    public UpdateObjetoPerdido setAlt(java.lang.String alt) {
      return (UpdateObjetoPerdido) super.setAlt(alt);
    }

    @Override
    public UpdateObjetoPerdido setFields(java.lang.String fields) {
      return (UpdateObjetoPerdido) super.setFields(fields);
    }

    @Override
    public UpdateObjetoPerdido setKey(java.lang.String key) {
      return (UpdateObjetoPerdido) super.setKey(key);
    }

    @Override
    public UpdateObjetoPerdido setOauthToken(java.lang.String oauthToken) {
      return (UpdateObjetoPerdido) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateObjetoPerdido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateObjetoPerdido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateObjetoPerdido setQuotaUser(java.lang.String quotaUser) {
      return (UpdateObjetoPerdido) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateObjetoPerdido setUserIp(java.lang.String userIp) {
      return (UpdateObjetoPerdido) super.setUserIp(userIp);
    }

    @Override
    public UpdateObjetoPerdido set(String parameterName, Object value) {
      return (UpdateObjetoPerdido) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Objetoperdidoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Objetoperdidoendpoint}. */
    @Override
    public Objetoperdidoendpoint build() {
      return new Objetoperdidoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ObjetoperdidoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setObjetoperdidoendpointRequestInitializer(
        ObjetoperdidoendpointRequestInitializer objetoperdidoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(objetoperdidoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
