/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-02 at 03:42:13 UTC 
 * Modify at your own risk.
 */

package com.mycompany.services.listaroendpoint.model;

/**
 * Model definition for ListarO.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the listaroendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ListarO extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String categoria;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer estado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lugar;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCategoria() {
    return categoria;
  }

  /**
   * @param categoria categoria or {@code null} for none
   */
  public ListarO setCategoria(java.lang.String categoria) {
    this.categoria = categoria;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getEstado() {
    return estado;
  }

  /**
   * @param estado estado or {@code null} for none
   */
  public ListarO setEstado(java.lang.Integer estado) {
    this.estado = estado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public ListarO setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLugar() {
    return lugar;
  }

  /**
   * @param lugar lugar or {@code null} for none
   */
  public ListarO setLugar(java.lang.String lugar) {
    this.lugar = lugar;
    return this;
  }

  @Override
  public ListarO set(String fieldName, Object value) {
    return (ListarO) super.set(fieldName, value);
  }

  @Override
  public ListarO clone() {
    return (ListarO) super.clone();
  }

}
