/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-03 at 01:00:08 UTC 
 * Modify at your own risk.
 */

package com.example.mateobadillo.ingesoft.objetoperdidoendpoint.model;

/**
 * Model definition for ObjetoPerdido.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the objetoperdidoendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ObjetoPerdido extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String categorias;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("codigo_usuario")
  private java.lang.String codigoUsuario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer estado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_usuario_sin_acceso")
  private java.lang.String idUsuarioSinAcceso;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lugar;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pregunta1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pregunta2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pregunta3;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String respuesta1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String respuesta2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String respuesta3;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCategorias() {
    return categorias;
  }

  /**
   * @param categorias categorias or {@code null} for none
   */
  public ObjetoPerdido setCategorias(java.lang.String categorias) {
    this.categorias = categorias;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCodigoUsuario() {
    return codigoUsuario;
  }

  /**
   * @param codigoUsuario codigoUsuario or {@code null} for none
   */
  public ObjetoPerdido setCodigoUsuario(java.lang.String codigoUsuario) {
    this.codigoUsuario = codigoUsuario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public ObjetoPerdido setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public ObjetoPerdido setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getEstado() {
    return estado;
  }

  /**
   * @param estado estado or {@code null} for none
   */
  public ObjetoPerdido setEstado(java.lang.Integer estado) {
    this.estado = estado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public ObjetoPerdido setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdUsuarioSinAcceso() {
    return idUsuarioSinAcceso;
  }

  /**
   * @param idUsuarioSinAcceso idUsuarioSinAcceso or {@code null} for none
   */
  public ObjetoPerdido setIdUsuarioSinAcceso(java.lang.String idUsuarioSinAcceso) {
    this.idUsuarioSinAcceso = idUsuarioSinAcceso;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLugar() {
    return lugar;
  }

  /**
   * @param lugar lugar or {@code null} for none
   */
  public ObjetoPerdido setLugar(java.lang.String lugar) {
    this.lugar = lugar;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public ObjetoPerdido setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPregunta1() {
    return pregunta1;
  }

  /**
   * @param pregunta1 pregunta1 or {@code null} for none
   */
  public ObjetoPerdido setPregunta1(java.lang.String pregunta1) {
    this.pregunta1 = pregunta1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPregunta2() {
    return pregunta2;
  }

  /**
   * @param pregunta2 pregunta2 or {@code null} for none
   */
  public ObjetoPerdido setPregunta2(java.lang.String pregunta2) {
    this.pregunta2 = pregunta2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPregunta3() {
    return pregunta3;
  }

  /**
   * @param pregunta3 pregunta3 or {@code null} for none
   */
  public ObjetoPerdido setPregunta3(java.lang.String pregunta3) {
    this.pregunta3 = pregunta3;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRespuesta1() {
    return respuesta1;
  }

  /**
   * @param respuesta1 respuesta1 or {@code null} for none
   */
  public ObjetoPerdido setRespuesta1(java.lang.String respuesta1) {
    this.respuesta1 = respuesta1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRespuesta2() {
    return respuesta2;
  }

  /**
   * @param respuesta2 respuesta2 or {@code null} for none
   */
  public ObjetoPerdido setRespuesta2(java.lang.String respuesta2) {
    this.respuesta2 = respuesta2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRespuesta3() {
    return respuesta3;
  }

  /**
   * @param respuesta3 respuesta3 or {@code null} for none
   */
  public ObjetoPerdido setRespuesta3(java.lang.String respuesta3) {
    this.respuesta3 = respuesta3;
    return this;
  }

  @Override
  public ObjetoPerdido set(String fieldName, Object value) {
    return (ObjetoPerdido) super.set(fieldName, value);
  }

  @Override
  public ObjetoPerdido clone() {
    return (ObjetoPerdido) super.clone();
  }

}
